services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - stock_network
  postgres:
    container_name: stock_b7156c-postgres-1
    networks:
      - stock_network

  scheduler:
    networks:
      - stock_network

  webserver:
    networks:
      - stock_network

  triggerer:
    networks:
      - stock_network

networks:
  stock_network:
    name: stock_network
    external: true