version: 2

sources:
  - name: raw
    database: stockwh
    schema: raw
    tables:
      - name: profile
      - name: price
      - name: news
      - name: income
      - name: balance
      - name: cash